### ISSUE TITLE
Issue: Function name mismatch

### ISSUE THREAD

**Issue by andywestuk** [Seagate/kinetic-c#10]
File: kinetic_admin_client.c

Function: void KineticClient_FreeLogInfo(KineticSession * const session,KineticLogInfo* info)
Should be: void KineticAdminClient_FreeLogInfo(KineticSession * const session,KineticLogInfo* info)

Header is defined as: void KineticAdminClient_FreeLogInfo(KineticSession * const session, KineticLogInfo* info);
Kind Regards
Andy

**Comment by liuxian9** [comment]
Thank you so much to point it out, Andy. 
I will fix it.
