### ISSUE TITLE
Issue Pointers: Kinetic_Version

### ISSUE THREAD

**Issue by andywestuk** [Seagate/kinetic-c#11]
Hi,

I think there's an issue with the function Kinetic_Version. 

The head says (kinetic_client.h)

> /**
>  * @brief Gets current version info of kinetic-c library
>  * 
>  * @return Returns a pointer to static version info
>  */

So I think the function prototype should change from 
> KineticVersionInfo KineticClient_Version(void);

to

> KineticVersionInfo* KineticClient_Version(void);

Within the source code it should change from

> KineticVersionInfo* KineticClient_Version(void)
> {
>     return VersionInfo;
> }

to 

> KineticVersionInfo* KineticClient_Version(void)
> {
>     return &VersionInfo;
> }

**Comment by liuxian9** [comment]
Thank you again, Andy.  
I will fix it.
