### ISSUE TITLE
KineticAdminClient_SetACL : Example ACL file?

### ISSUE THREAD

**Issue by andywestuk** [Seagate/kinetic-c#13]
Hi,

I'm probably missed something in the source tree, but...

Is there an example of the JSON file structure and definitions of the elements within the structure?

Also, for a point of clarification. When this command is sent will it overwrite the entire ACL on the device with this list, or append the data on the device with the new list?

Cheers
Andy

**Comment by jphughes** [comment]
> On Mar 30, 2015, at 4:56 PM, Andy West <notifications@github.com> wrote:
> 
> Hi,
> 
> I'm probably missed something in the source tree, but...
> 
> Is there an example of the JSON file structure and definitions of the elements within the structure?
> 
This will be added to the repository soon. We are working on this. 
> Also, for a point of clarification. When this command is sent will it overwrite the entire ACL on the device with this list, or append the data on the device with the new list?
> 

Overwrite.

**Comment by andywestuk** [comment]
Thanks for the clarification.  :-)

Are these any plans for a GetACL command, so that we can append the list without destroying any customer information (for example during a warranty process)

Cheers 
Andy

**Comment by jphughes** [comment]
There are no plans for getACL. If customers ask, maybe. 

Sensitive information like the keys in the ACL are things that customers would want to keep to themselves. The customers would have this information, so if they wanted to share with a data recovery company, they can.

**Comment by liuxian9** [comment]
I will add the example to the c library repository.

On Mar 30, 2015, at 16:30, James Hughes <notifications@github.com> wrote:





> On Mar 30, 2015, at 4:56 PM, Andy West <notifications@github.com> wrote:
>
> Hi,
>
> I'm probably missed something in the source tree, but...
>
> Is there an example of the JSON file structure and definitions of the
elements within the structure?
>
This will be added to the repository soon. We are working on this.
> Also, for a point of clarification. When this command is sent will it
overwrite the entire ACL on the device with this list, or append the data
on the device with the new list?
>

Overwrite.

> Cheers
> Andy
>
> —
> Reply to this email directly or view it on GitHub.
>

—
Reply to this email directly or view it on GitHub
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Seagate_kinetic-2Dc_issues_13-23issuecomment-2D87590659&d=AwMFaQ&c=IGDlg0lD0b-nebmJJ0Kp8A&r=EUuuxonrJUirjxCRFrVbkMYoAbzaSNvWHCt7EjedD9Y&m=8jMGprWNyfOS_Ax8tRp4LB70uUSUE9lTckw2YiwgMVs&s=9GLSB-EKKpW98GVGedFCzkkVs8bKVzqXahlT0yMHy5U&e=>
.

**Comment by liuxian9** [comment]
I just wanted to add some examples of the JSON file structure and definitions, but, actually, the c library has already added many examples.  Please find those examples from https://github.com/Seagate/kinetic-c/tree/master/test/unit/acl.
