### ISSUE TITLE
TLS messages lager than 14KB

### ISSUE THREAD

**Issue by rcrane** [Seagate/kinetic-c#53]
It appears that the disk (not the simulator) is not able to handle write requests through TLS that are larger than 14427 bytes. The disk will terminate the session and reply with an operation failed error.

To demonstrate the issue and a workaround, I have created this repo:

https://github.com/rcrane/kinetic_tls_bug

Still puzzling is that writing an object of 15KB through TLS fails but continuously writing objects with increasing size (starting at sizes below 14KB) can circumvent the bug.

**Comment by chiaming2000** [comment]
Would you please provide the drive firmware version that caused the issue?
Many thanks.

**Comment by rcrane** [comment]
model: ST4000NK001-1NX668
version: 03.00.01
compilationDate: Thu May 28 08:44:00 MDT 2015
protocolVersion: 3.0.6
protocolCompilationDate: Thu May 28 08:44:00 MDT 2015

**Comment by chiaming2000** [comment]
It is under review within the drive firmware team.  Will update the status when there is a resolution.
Thanks.

**Comment by rcrane** [comment]
Minor remark: Setting the TCP sending buffer (kinetic_socket.c, line 101) to 14000 didn't impact the described behavior.

**Comment by rcrane** [comment]
@chiaming2000 Are there any news about the issue?

**Comment by chiaming2000** [comment]
Thanks for the message. Seagate firmware team is aware of the issue and will respond to this shortly.

**Comment by tdeh** [comment]
@rcrane I'm on the Kinetic firmware team and have replicated this bug on a 1st gen, 4TB Kinetic drive. I also confirmed that we have fixed this bug for our 2nd gen, 8TB Kinetic drive. Unfortunately, we no longer are supporting the 1st gen drive so we do not plan on providing a fix.
